'''
A simple script that transforms txt file to vector databse file.
The txt file is generated by json2sqlite by Paul.

Rui Xue, r.xue@cern.ch
Nov, 2025
'''

import re
import shutil
from pathlib import Path
from langchain_core.documents import Document
from langchain_huggingface import HuggingFaceEmbeddings
from langchain_chroma import Chroma

curr_dir = Path(__file__).parent
target_dir = curr_dir.parent / "resources"
inputfile = target_dir / "cric_schema.txt"
embedder = HuggingFaceEmbeddings(model_name="all-MiniLM-L6-v2")

def ToVecDB():
    with open(inputfile, "r") as f:
        schema_txt = f.read()

    schema_parse = []
    schema_lines = schema_txt.splitlines()
    table_name = re.match(r"Table\s+(\w+)", schema_lines[0]).group(1)

    print("Table Name: ", table_name)
    f.close()
    for line in schema_lines[1:]:
        line = line.strip()

        match_field = re.match(r"[-•]\s+([\w_]+)\s+(\w+)(.*)", line)

        # stop when out of queuedata range
        if not match_field:
            break
        field = match_field.group(1)
        datatype = match_field.group(2)
        rest = match_field.group(3).strip() if match_field.group(3) else ""

        text = None
        if rest:
            text = f"Table {table_name} field {field} type {datatype} example {rest}."
        else:        
            text = f"Table {table_name} field {field} type {datatype}."

        schema_parse.append(
            Document(page_content=text, metadata={"table": table_name, "field": field, 
                                                "type": datatype, "example": rest})
        )
    # remove the existing vector db
    if (target_dir / "schemaDB").exists():
        shutil.rmtree(target_dir / "schemaDB")
    # save the new vector db
    Chroma.from_documents(schema_parse, embedder, persist_directory=str(target_dir / "schemaDB"))
    print( "Txt 2 Database Transformation Finished.")
    f.close()
    return

def checkDB(field:str):
    db = Chroma(persist_directory = str(target_dir / "schemaDB"), embedding_function = embedder)
    # search for a specific field
    results = db.get(where={"field": field})
    if not results["ids"]:
        print(f"This field {field} doesnt exist")
        return
    else:
        for i, (content, meta) in enumerate(zip(results["documents"], results["metadatas"]), 1):
            print(f"{meta}")
    return

if __name__ == "__main__":
    ToVecDB()
    checkDB("CoCo")
    checkDB("copytools")